# Generated by Django 3.0.5 on 2020-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200922_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
